// Sample data for the investor dashboard

import type { Position, Offer } from "./types";

export const SAMPLE_POSITIONS: Position[] = [
  {
    id: "p1",
    property: "Loft Reforma 210",
    location: "CDMX • Juárez",
    advance: 89243,
    rent: 10000,
    termMonths: 12,
    irrAPR: 0.77,
    nextPayment: "28 Oct",
    stream: "Healthy",
    status: "Active",
  },
  {
    id: "p2",
    property: "Casa Lomas 34",
    location: "CDMX • Lomas",
    advance: 118000,
    rent: 12000,
    termMonths: 10,
    irrAPR: 0.52,
    nextPayment: "03 Nov",
    stream: "Delayed",
    status: "Active",
  },
  {
    id: "p3",
    property: "Depto Roma Nte 88",
    location: "CDMX • Roma",
    advance: 76000,
    rent: 8000,
    termMonths: 12,
    irrAPR: 0.45,
    nextPayment: "19 Oct",
    stream: "Healthy",
    status: "Completed",
  },
];

export const SAMPLE_OFFERS: Offer[] = [
  {
    id: "o1",
    property: "PH Coyoacán 12",
    location: "CDMX • Coyoacán",
    advance: 81200,
    rent: 9000,
    irrAPR: 0.61,
    termMonths: 12,
    ocPct: 10,
    haircutPct: 10,
    chain: "Base",
    currency: "USDC/MXN",
    riskTier: "A",
    tenantScore: "A-",
    propertyScore: "A",
    esignHash: "0x7a…e2",
    attestations: 4,
  },
  {
    id: "o2",
    property: "Loft Condesa 5",
    location: "CDMX • Condesa",
    advance: 65600,
    rent: 7000,
    irrAPR: 0.72,
    termMonths: 9,
    ocPct: 12,
    haircutPct: 8,
    chain: "Base",
    currency: "USDC/MXN",
    riskTier: "B",
    tenantScore: "B+",
    propertyScore: "A-",
    esignHash: "0x3f…91",
    attestations: 3,
  },
  {
    id: "o3",
    property: "Casa Del Valle 27",
    location: "CDMX • Del Valle",
    advance: 124000,
    rent: 13500,
    irrAPR: 0.49,
    termMonths: 15,
    ocPct: 15,
    haircutPct: 12,
    chain: "Base",
    currency: "USDC/MXN",
    riskTier: "A",
    tenantScore: "A",
    propertyScore: "A",
    esignHash: "0xa1…c4",
    attestations: 5,
  },
];
